name: rrpredictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - selenium
  - chromedriver-binary
  - psutil
  - requests
  - beautifulsoup4
  - python-chromedriver-binary
